-- Slack Routing & Approvals
-- Adds the slack_approvals table to persist approval state for inbound customer
-- messages that require human review before an automated response is dispatched.
-- Also adds slack_routing_rules for configurable keyword/intent-based routing.

-- ─── slack_approvals ────────────────────────────────────────────────────────
-- One row per approval request generated by the Slack routing layer.
-- Linked to customer_content so the original message is always traceable.
CREATE TABLE IF NOT EXISTS slack_approvals (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id           UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  customer_tenant_id  UUID REFERENCES customer_tenants(id) ON DELETE SET NULL,
  content_id          UUID REFERENCES customer_content(id) ON DELETE SET NULL,
  kind                TEXT NOT NULL DEFAULT 'message'
                        CHECK (kind IN ('message', 'file', 'request', 'escalation')),
  -- The routed destination derived from the routing rules (e.g. 'support', 'billing')
  destination         TEXT NOT NULL DEFAULT 'support',
  -- Snapshot of the content for standalone querying without joins
  payload             JSONB NOT NULL DEFAULT '{}',
  status              TEXT NOT NULL DEFAULT 'pending'
                        CHECK (status IN ('pending', 'approved', 'rejected', 'expired')),
  -- Slack coordinates for the source message
  slack_channel_id    TEXT,
  slack_message_ts    TEXT,
  -- Decision metadata
  decision_by         TEXT,
  decision_at         TIMESTAMPTZ,
  decision_reason     TEXT,
  -- Expiry: approvals older than this are auto-expired
  expires_at          TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '72 hours'),
  created_at          TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at          TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_slack_approvals_tenant         ON slack_approvals(tenant_id);
CREATE INDEX IF NOT EXISTS idx_slack_approvals_customer_tenant ON slack_approvals(customer_tenant_id);
CREATE INDEX IF NOT EXISTS idx_slack_approvals_status          ON slack_approvals(status) WHERE status = 'pending';
CREATE INDEX IF NOT EXISTS idx_slack_approvals_content         ON slack_approvals(content_id);
CREATE INDEX IF NOT EXISTS idx_slack_approvals_expires         ON slack_approvals(expires_at) WHERE status = 'pending';

-- ─── slack_routing_rules ─────────────────────────────────────────────────────
-- Tenant-configurable routing rules that map message keywords or intent labels
-- to a destination (e.g. 'billing', 'engineering', 'support', 'sales').
-- Rules are evaluated in priority order (lower number = higher priority).
CREATE TABLE IF NOT EXISTS slack_routing_rules (
  id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id     UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
  pattern       TEXT NOT NULL,          -- keyword or regex fragment to match
  destination   TEXT NOT NULL,          -- where to route matching messages
  intent_label  TEXT,                   -- optional human-readable intent label
  requires_approval BOOLEAN NOT NULL DEFAULT false,
  priority      INT NOT NULL DEFAULT 100,
  is_active     BOOLEAN NOT NULL DEFAULT true,
  created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_slack_routing_rules_tenant   ON slack_routing_rules(tenant_id);
CREATE INDEX IF NOT EXISTS idx_slack_routing_rules_active   ON slack_routing_rules(tenant_id, is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_slack_routing_rules_priority ON slack_routing_rules(tenant_id, priority) WHERE is_active = true;
