steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'docker/Dockerfile.scheduler', '-t', 'us-central1-docker.pkg.dev/ai-glyphor-company/cloud-run-source-deploy/scheduler:latest', '.']
images:
  - 'us-central1-docker.pkg.dev/ai-glyphor-company/cloud-run-source-deploy/scheduler:latest'
