FROM mcr.microsoft.com/playwright:v1.58.2-noble

WORKDIR /app

COPY services/playwright-service/package*.json ./
RUN npm install --omit=dev

COPY services/playwright-service/server.js ./server.js

ENV PORT=8080
EXPOSE 8080

CMD ["node", "server.js"]