import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { execFile as execFileCallback } from 'node:child_process';
import { promisify } from 'node:util';
import OpenAI from 'openai';

const execFile = promisify(execFileCallback);

/**
 * Sandbox Build Validator
 *
 * Preferred path: OpenAI hosted shell containers. This uses the same vendor as
 * the generation model and avoids a second sandbox provider.
 *
 * Fallback path: E2B microVM if hosted shell is unavailable or blocked by org
 * allowlist / network policy.
 *
 * OpenAI envs checked in order:
 *   OPENAI_ADMIN_KEY_WEB_BUILD
 *   OPENAI_ADMIN_KEY_COMPANY
 *   OPENAI_API_KEY
 *
 * E2B envs:
 *   E2B_API_KEY
 *   E2B_TEMPLATE_ID
 *
 * Optional:
 *   SANDBOX_BUILD_SKIP=true
 */

export interface SandboxBuildResult {
  ok: boolean;
  stdout: string;
  stderr: string;
  /** Extracted actionable error lines, capped at 60. */
  errors: string[];
  /** True when sandbox validation was intentionally skipped. */
  skipped: boolean;
  reason?: string;
  durationMs?: number;
}

// ─── Template fixed files ─────────────────────────────────────────────────────
// Files present in the GitHub repo but NOT generated by the model.
// The model generates index.html, src/App.tsx, src/styles/*, and src/components/*.

const TEMPLATE_PACKAGE_JSON = JSON.stringify({
  name: 'glyphor-web-project',
  private: true,
  version: '0.1.0',
  type: 'module',
  scripts: {
    build: 'tsc --noEmit && vite build',
    typecheck: 'tsc --noEmit',
  },
  dependencies: {
    '@radix-ui/react-toast': '^1.2.15',
    '@radix-ui/react-tooltip': '^1.2.8',
    '@tanstack/react-query': '^5.90.5',
    'class-variance-authority': '^0.7.1',
    clsx: '^2.1.1',
    'framer-motion': '^12.23.24',
    'lucide-react': '^0.542.0',
    react: '^19.1.1',
    'react-dom': '^19.1.1',
    'tailwind-merge': '^3.3.1',
  },
  devDependencies: {
    '@types/node': '^22.18.6',
    '@types/react': '^19.1.16',
    '@types/react-dom': '^19.1.9',
    '@vitejs/plugin-react-swc': '^4.1.0',
    tailwindcss: '^4.1.12',
    typescript: '^5.9.2',
    vite: '^7.1.7',
  },
}, null, 2);

const TEMPLATE_TSCONFIG = `{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "allowImportingTsExtensions": false,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true,
    "baseUrl": ".",
    "paths": {
      "@/components/*": ["src/components/*"],
      "@/hooks/*": ["src/hooks/*"],
      "@/lib/*": ["src/lib/*"],
      "@/styles/*": ["src/styles/*"]
    }
  },
  "include": ["src", "vite.config.ts"]
}`;

const TEMPLATE_VITE_CONFIG = `import path from 'node:path';
import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react-swc';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@/components': path.resolve(__dirname, 'src/components'),
      '@/hooks': path.resolve(__dirname, 'src/hooks'),
      '@/lib': path.resolve(__dirname, 'src/lib'),
      '@/styles': path.resolve(__dirname, 'src/styles'),
    },
  },
});`;

const TEMPLATE_MAIN_TSX = `import { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './styles/index.css';
import { App } from './App';

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
);`;

const TEMPLATE_LIB_UTILS = `import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}`;

/** Fixed files that scaffold the build — written first, then model files override. */
export const SANDBOX_TEMPLATE_FILES: Record<string, string> = {
  'package.json': TEMPLATE_PACKAGE_JSON,
  'tsconfig.json': TEMPLATE_TSCONFIG,
  'vite.config.ts': TEMPLATE_VITE_CONFIG,
  'src/main.tsx': TEMPLATE_MAIN_TSX,
  'src/lib/utils.ts': TEMPLATE_LIB_UTILS,
};

const OPENAI_SHELL_ALLOWED_DOMAINS = ['registry.npmjs.org'];

// ─── Error parsing ─────────────────────────────────────────────────────────────

export function parseSandboxErrors(output: string): string[] {
  const lines = output.split('\n');
  const errors: string[] = [];

  for (const line of lines) {
    const t = line.trim();
    if (!t) continue;
    if (
      /error ts\d+/i.test(t) ||
      /^✘\s*\[error\]/i.test(t) ||
      /^[×✗]\s/.test(t) ||
      /could not resolve/i.test(t) ||
      /transform failed/i.test(t) ||
      /build failed/i.test(t) ||
      /module not found/i.test(t) ||
      /is not assignable to/i.test(t) ||
      /cannot find module/i.test(t) ||
      /cannot find name/i.test(t) ||
      /has no exported member/i.test(t) ||
      /property .* does not exist/i.test(t) ||
      /type.*is not/i.test(t) && /error/i.test(t) ||
      /^(src|components?)\/.+\(\d+,\d+\): error/.test(t)
    ) {
      errors.push(t);
    }
  }

  if (errors.length === 0) {
    // No structured errors found — return last 40 lines of output for context
    errors.push(...lines.filter(l => l.trim()).slice(-40));
  }

  return errors.slice(0, 60);
}

// ─── Main export ──────────────────────────────────────────────────────────────

/**
 * Runs generated website files through a real Vite + TypeScript build in an
 * E2B microVM sandbox. Returns `SandboxBuildResult.ok = true` if the build
 * is clean, or structured errors the model can use to self-repair.
 *
 * Skips gracefully (ok = true, skipped = true) when E2B_API_KEY is absent.
 */
export async function runSandboxBuild(
  generatedFiles: Record<string, string>,
  signal?: AbortSignal,
): Promise<SandboxBuildResult> {
  if (process.env.SANDBOX_BUILD_SKIP === 'true') {
    return {
      ok: true,
      stdout: '',
      stderr: '',
      errors: [],
      skipped: true,
      reason: 'SANDBOX_BUILD_SKIP=true — skipping.',
    };
  }

  const openAiResult = await runOpenAIHostedShellBuild(generatedFiles, signal);
  if (!openAiResult.skipped) {
    return openAiResult;
  }

  const e2bResult = await runE2BBuild(generatedFiles, signal);
  if (!e2bResult.skipped) {
    return e2bResult;
  }

  return {
    ok: true,
    stdout: '',
    stderr: '',
    errors: [],
    skipped: true,
    reason: [openAiResult.reason, e2bResult.reason].filter(Boolean).join(' | ') || 'No sandbox backend configured.',
  };
}

async function runOpenAIHostedShellBuild(
  generatedFiles: Record<string, string>,
  signal?: AbortSignal,
): Promise<SandboxBuildResult> {
  const apiKey = getOpenAIKey();
  if (!apiKey) {
    return buildSkipped('No OpenAI API key available for hosted shell.');
  }

  const startMs = Date.now();
  const tempRoot = await mkdtemp(path.join(os.tmpdir(), 'glyphor-shell-'));
  const projectDir = path.join(tempRoot, 'project');
  const tarPath = path.join(tempRoot, 'project.tgz');

  try {
    const allFiles = { ...SANDBOX_TEMPLATE_FILES, ...generatedFiles };
    await materializeFiles(projectDir, allFiles);
    await createTarball(projectDir, tarPath);

    const client = new OpenAI({ apiKey });
    const container = await client.containers.create({
      name: 'glyphor-web-build',
      expires_after: { anchor: 'last_active_at', minutes: 20 },
    });

    const uploaded = await client.containers.files.create(container.id, {
      file: await OpenAI.fileFromPath(tarPath),
    });

    if (signal?.aborted) return buildSkipped('Aborted');

    const response = await (client.responses.create as (body: any) => Promise<any>)({
      model: 'gpt-5.4',
      tools: [
        {
          type: 'shell',
          environment: {
            type: 'container_reference',
            container_id: container.id,
            network_policy: {
              type: 'allowlist',
              allowed_domains: OPENAI_SHELL_ALLOWED_DOMAINS,
            },
          },
        },
      ],
      tool_choice: 'required',
      max_output_tokens: 4096,
      input: [
        {
          role: 'user',
          content: [
            {
              type: 'input_text',
              text: [
                'In the hosted shell container, run these exact steps and do not do anything else:',
                `1. mkdir -p /mnt/data/app`,
                `2. tar -xzf ${uploaded.path} -C /mnt/data/app`,
                '3. cd /mnt/data/app',
                '4. npm install --prefer-offline --no-audit --no-fund',
                '5. npm run build',
                '',
                'Return the shell output. Do not summarize or omit stderr.',
              ].join('\n'),
            },
          ],
        },
      ],
    });

    const shellText = extractShellText(response);
    const combined = [shellText.stdout, shellText.stderr, response.output_text ?? ''].filter(Boolean).join('\n').trim();

    if (shellText.exitCode === 0) {
      return {
        ok: true,
        stdout: shellText.stdout,
        stderr: shellText.stderr,
        errors: [],
        skipped: false,
        durationMs: Date.now() - startMs,
      };
    }

    return {
      ok: false,
      stdout: shellText.stdout,
      stderr: shellText.stderr || combined,
      errors: parseSandboxErrors(combined),
      skipped: false,
      durationMs: Date.now() - startMs,
    };
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    const lower = message.toLowerCase();
    if (signal?.aborted || /aborted/.test(lower)) {
      return buildSkipped('Aborted');
    }

    if (
      /allowlist|allowed_domains|network_policy|hosted shell|container_auto|container_reference|not available|unsupported/i.test(message)
    ) {
      console.warn(`[SandboxBuild] OpenAI hosted shell unavailable, falling back: ${message}`);
      return buildSkipped(`OpenAI hosted shell unavailable: ${message}`);
    }

    return {
      ok: false,
      stdout: '',
      stderr: message,
      errors: [`OpenAI hosted shell error: ${message}`],
      skipped: false,
      durationMs: Date.now() - startMs,
    };
  } finally {
    await rm(tempRoot, { recursive: true, force: true }).catch(() => {});
  }
}

async function runE2BBuild(
  generatedFiles: Record<string, string>,
  signal?: AbortSignal,
): Promise<SandboxBuildResult> {
  const apiKey = process.env.E2B_API_KEY?.trim();
  if (!apiKey) {
    return buildSkipped('E2B_API_KEY not set — skipping E2B sandbox build validation.');
  }

  // Dynamic import so missing E2B package doesn't break cold starts
  let SandboxClass: { create: (opts?: Record<string, unknown>) => Promise<SandboxInstance> };
  try {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const mod = await import('e2b') as any;
    SandboxClass = mod.default ?? mod.Sandbox;
    if (!SandboxClass?.create) throw new Error('E2B Sandbox.create not found');
  } catch (err) {
    return {
      ok: true, stdout: '', stderr: '', errors: [], skipped: true,
      reason: `E2B SDK unavailable: ${(err as Error).message}`,
    };
  }

  const projectDir = '/home/user/app';
  const templateId = process.env.E2B_TEMPLATE_ID?.trim();
  let sandbox: SandboxInstance | null = null;
  const startMs = Date.now();

  try {
    console.log('[SandboxBuild] Creating sandbox…');
    sandbox = await SandboxClass.create({
      apiKey,
      ...(templateId ? { template: templateId } : {}),
      timeoutMs: 360_000,
    });

    if (signal?.aborted) return buildSkipped('Aborted');

    // Write all template files then model-generated files (model takes precedence)
    const allFiles = { ...SANDBOX_TEMPLATE_FILES, ...generatedFiles };
    console.log(`[SandboxBuild] Writing ${Object.keys(allFiles).length} files…`);

    await sandbox.commands.run(`mkdir -p ${projectDir}/src/components ${projectDir}/src/styles ${projectDir}/src/lib ${projectDir}/src/hooks`);

    for (const [filePath, content] of Object.entries(allFiles)) {
      const fullPath = `${projectDir}/${filePath}`;
      const dir = fullPath.slice(0, fullPath.lastIndexOf('/'));
      if (dir !== projectDir) {
        await sandbox.commands.run(`mkdir -p "${dir}"`);
      }
      await sandbox.files.write(fullPath, content);
    }

    if (signal?.aborted) return buildSkipped('Aborted after file write');

    // npm install — uses cached node_modules if E2B_TEMPLATE_ID is a pre-built image
    console.log('[SandboxBuild] npm install…');
    const installResult = await sandbox.commands.run(
      `cd ${projectDir} && npm install --prefer-offline --no-audit --no-fund 2>&1`,
      { timeoutMs: 180_000 },
    );
    const installOut = combine(installResult);

    if ((installResult.exitCode ?? 0) !== 0) {
      const errors = parseSandboxErrors(`npm install failed:\n${installOut}`);
      console.warn(`[SandboxBuild] npm install failed (${errors.length} errors)`);
      return { ok: false, stdout: installResult.stdout ?? '', stderr: installResult.stderr ?? '', errors, skipped: false, durationMs: Date.now() - startMs };
    }

    if (signal?.aborted) return buildSkipped('Aborted after npm install');

    // Run the real build: tsc --noEmit && vite build
    console.log('[SandboxBuild] npm run build…');
    const buildResult = await sandbox.commands.run(
      `cd ${projectDir} && npm run build 2>&1`,
      { timeoutMs: 120_000 },
    );
    const buildOut = combine(buildResult);
    const exitCode = buildResult.exitCode ?? 0;
    console.log(`[SandboxBuild] build exited ${exitCode} in ${Date.now() - startMs}ms`);

    if (exitCode !== 0) {
      const errors = parseSandboxErrors(buildOut);
      return { ok: false, stdout: buildResult.stdout ?? '', stderr: buildResult.stderr ?? '', errors, skipped: false, durationMs: Date.now() - startMs };
    }

    return { ok: true, stdout: buildResult.stdout ?? '', stderr: '', errors: [], skipped: false, durationMs: Date.now() - startMs };
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    if (signal?.aborted || /aborted/i.test(msg)) return buildSkipped('Aborted');
    console.error('[SandboxBuild] Error:', msg);
    return { ok: false, stdout: '', stderr: msg, errors: [`Sandbox error: ${msg}`], skipped: false, durationMs: Date.now() - startMs };
  } finally {
    if (sandbox) await sandbox.kill().catch(() => {});
  }
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

async function materializeFiles(rootDir: string, files: Record<string, string>): Promise<void> {
  for (const [filePath, content] of Object.entries(files)) {
    const fullPath = path.join(rootDir, filePath);
    await mkdirp(path.dirname(fullPath));
    await writeFile(fullPath, content, 'utf8');
  }
}

async function mkdirp(dirPath: string): Promise<void> {
  const { mkdir } = await import('node:fs/promises');
  await mkdir(dirPath, { recursive: true });
}

async function createTarball(sourceDir: string, tarPath: string): Promise<void> {
  await execFile('tar', ['-czf', tarPath, '-C', sourceDir, '.']);
}

function getOpenAIKey(): string | null {
  return process.env.OPENAI_ADMIN_KEY_WEB_BUILD?.trim()
    || process.env.OPENAI_ADMIN_KEY_COMPANY?.trim()
    || process.env.OPENAI_API_KEY?.trim()
    || null;
}

function extractShellText(response: unknown): { stdout: string; stderr: string; exitCode: number | null } {
  const outputItems = Array.isArray((response as { output?: unknown[] })?.output)
    ? ((response as { output: unknown[] }).output as Array<Record<string, unknown>>)
    : [];

  const stdoutChunks: string[] = [];
  const stderrChunks: string[] = [];
  let exitCode: number | null = null;

  for (const item of outputItems) {
    if (item.type !== 'shell_call_output') continue;
    const outputs = Array.isArray(item.output) ? item.output as Array<Record<string, unknown>> : [];
    for (const out of outputs) {
      const stdout = typeof out.stdout === 'string' ? out.stdout : '';
      const stderr = typeof out.stderr === 'string' ? out.stderr : '';
      if (stdout) stdoutChunks.push(stdout);
      if (stderr) stderrChunks.push(stderr);
      const outcome = (out.outcome ?? {}) as Record<string, unknown>;
      if (outcome.type === 'exit' && typeof outcome.exit_code === 'number') {
        exitCode = outcome.exit_code;
      }
    }
  }

  return {
    stdout: stdoutChunks.join('\n').trim(),
    stderr: stderrChunks.join('\n').trim(),
    exitCode,
  };
}

interface SandboxInstance {
  commands: { run: (cmd: string, opts?: { timeoutMs?: number }) => Promise<{ stdout?: string; stderr?: string; exitCode?: number }> };
  files: { write: (path: string, content: string) => Promise<void> };
  kill: () => Promise<void>;
}

function combine(r: { stdout?: string; stderr?: string }): string {
  return `${r.stdout ?? ''}\n${r.stderr ?? ''}`.trim();
}

function buildSkipped(reason: string): SandboxBuildResult {
  return { ok: true, stdout: '', stderr: '', errors: [], skipped: true, reason };
}
