import type { Capability } from './capabilities.js';

export const TOOL_CAPABILITY_MAP: Record<string, readonly Capability[]> = {
  get_file_contents: ['code_generation'],
  create_or_update_file: ['code_generation', 'needs_apply_patch'],
  create_branch: ['code_generation'],
  create_frontend_pr: ['code_generation'],
  search_code: ['code_generation'],
  run_lighthouse: ['visual_analysis'],
  screenshot_page: ['visual_analysis'],
  screenshot_component: ['visual_analysis'],
  web_search: ['web_research', 'needs_citations'],
  web_fetch: ['web_research', 'needs_citations'],
  submit_research_packet: ['web_research', 'needs_citations'],
  get_compliance_status: ['legal_reasoning', 'needs_citations'],
  get_contracts: ['legal_reasoning', 'needs_citations'],
  create_contract: ['legal_reasoning', 'needs_citations'],
  get_financials: ['financial_computation'],
  get_revenue_forecast: ['financial_computation', 'needs_code_execution'],
  get_customer_ltv: ['financial_computation', 'needs_code_execution'],
  calculate_unit_economics: ['financial_computation', 'needs_code_execution'],
  get_margin_analysis: ['financial_computation', 'needs_code_execution'],
  evaluate_assignment: ['nuanced_evaluation'],
  evaluate_team_output: ['nuanced_evaluation'],
  review_team_output: ['nuanced_evaluation'],
  read_founder_directives: ['orchestration'],
  create_work_assignments: ['orchestration'],
  dispatch_assignment: ['orchestration'],
  synthesize_team_deliverable: ['orchestration'],
  get_figma_file: ['structured_extraction'],
  get_figma_components: ['structured_extraction'],
  list_components: ['structured_extraction'],
  query_agent_runs: ['structured_extraction', 'low_complexity'],
  query_agent_health: ['structured_extraction', 'low_complexity'],
  query_data_sync_status: ['structured_extraction', 'low_complexity'],
  send_agent_message: ['simple_tool_calling'],
  who_handles: ['simple_tool_calling'],
  get_agent_directory: ['simple_tool_calling'],
};
