import type { Capability } from './capabilities.js';

export const TOOL_CAPABILITY_MAP: Record<string, readonly Capability[]> = {
  // Core universal tools intentionally omitted:
  // save_memory, recall_memories, search_memories, read_my_assignments,
  // submit_assignment_output, flag_assignment_blocker, send_agent_message,
  // check_messages, call_meeting, log_activity, request_tool_access,
  // request_new_tool, emit_insight, emit_alert, send_teams_dm, read_teams_dm,
  // publish_deliverable, get_deliverables.

  // Code + engineering
  get_file_contents: ['structured_extraction'],
  create_or_update_file: ['code_generation', 'needs_apply_patch'],
  create_branch: ['code_generation'],
  create_github_pr: ['code_generation'],
  merge_github_pr: ['code_generation'],
  github_create_pull_request: ['code_generation'],
  github_get_pull_request_status: ['structured_extraction'],
  github_wait_for_pull_request_checks: ['structured_extraction'],
  github_merge_pull_request: ['code_generation'],
  create_github_issue: ['simple_tool_calling'],
  deploy_to_staging: ['code_generation'],
  read_file: ['structured_extraction'],
  create_frontend_pr: ['code_generation'],
  read_frontend_file: ['structured_extraction'],
  search_frontend_code: ['structured_extraction'],
  list_frontend_files: ['structured_extraction'],
  write_frontend_file: ['code_generation'],
  create_design_branch: ['code_generation'],
  create_git_branch: ['code_generation'],
  scaffold_component: ['code_generation'],
  scaffold_page: ['code_generation'],
  clone_and_modify: ['code_generation'],
  deploy_preview: ['code_generation'],
  codex: ['code_generation'],
  'codex-reply': ['code_generation'],
  normalize_design_brief: ['creative_writing'],
  invoke_web_build: ['code_generation'],
  invoke_web_iterate: ['code_generation'],
  invoke_web_upgrade: ['code_generation'],
  build_website_foundation: ['code_generation'],
  github_create_from_template: ['code_generation'],
  github_push_files: ['code_generation'],
  vercel_create_project: ['code_generation'],
  vercel_get_preview_url: ['structured_extraction'],
  vercel_get_production_url: ['structured_extraction'],
  cloudflare_register_preview: ['code_generation'],
  cloudflare_update_preview: ['code_generation'],
  run_test_suite: ['code_generation'],
  create_test_plan: ['code_generation'],
  search_code: ['structured_extraction'],
  get_code_coverage: ['structured_extraction'],
  get_quality_metrics: ['structured_extraction'],
  check_build_errors: ['structured_extraction'],
  check_bundle_size: ['structured_extraction'],
  get_container_logs: ['structured_extraction'],
  get_build_queue: ['structured_extraction'],
  get_deployment_history: ['structured_extraction'],
  get_deployment_status: ['structured_extraction'],
  list_deployments: ['structured_extraction'],
  get_infrastructure_inventory: ['structured_extraction'],
  get_service_dependencies: ['structured_extraction'],
  check_pr_status: ['structured_extraction'],
  get_github_pr_status: ['structured_extraction'],
  get_ci_health: ['structured_extraction'],
  get_repo_stats: ['structured_extraction'],
  get_repo_code_health: ['structured_extraction'],
  query_build_logs: ['structured_extraction'],
  query_error_patterns: ['structured_extraction'],
  query_test_results: ['structured_extraction'],
  get_pipeline_runs: ['structured_extraction'],
  get_recent_commits: ['structured_extraction'],

  // Visual + design
  run_lighthouse: ['visual_analysis'],
  run_lighthouse_batch: ['visual_analysis'],
  screenshot_page: ['visual_analysis'],
  screenshot_component: ['visual_analysis'],
  compare_screenshots: ['visual_analysis'],
  check_responsive: ['visual_analysis'],
  run_lighthouse_audit: ['visual_analysis'],
  run_accessibility_audit: ['visual_analysis'],
  check_ai_smell: ['visual_analysis'],
  validate_brand_compliance: ['visual_analysis'],
  get_design_quality_summary: ['visual_analysis'],
  validate_tokens_vs_implementation: ['visual_analysis'],
  storybook_screenshot: ['visual_analysis'],
  storybook_screenshot_all: ['visual_analysis'],
  storybook_visual_diff: ['visual_analysis'],
  pulse_analyze_image_for_video: ['visual_analysis'],
  get_design_tokens: ['structured_extraction'],
  get_component_library: ['structured_extraction'],
  get_template_registry: ['structured_extraction'],
  list_templates: ['structured_extraction'],
  get_color_palette: ['structured_extraction'],
  get_typography_scale: ['structured_extraction'],
  list_components: ['structured_extraction'],
  get_component_usage: ['structured_extraction'],
  update_design_token: ['simple_tool_calling'],
  storybook_list_stories: ['structured_extraction'],
  storybook_check_coverage: ['structured_extraction'],
  storybook_get_story_source: ['structured_extraction'],
  storybook_save_baseline: ['code_generation'],

  // Research
  web_search: ['web_research', 'needs_citations'],
  web_fetch: ['web_research', 'needs_citations'],
  submit_research_packet: ['web_research', 'needs_citations'],
  search_news: ['web_research', 'needs_citations'],
  search_hacker_news: ['web_research', 'needs_citations'],
  search_product_hunt: ['web_research', 'needs_citations'],
  fetch_github_releases: ['web_research', 'needs_citations'],
  fetch_pricing_pages: ['web_research', 'needs_citations'],
  save_research: ['simple_tool_calling'],
  search_research: ['structured_extraction'],
  get_research_timeline: ['structured_extraction'],
  create_research_brief: ['web_research'],
  create_monitor: ['simple_tool_calling'],
  check_monitors: ['structured_extraction'],
  get_monitor_history: ['web_research'],
  track_competitor_product: ['web_research'],
  search_academic_papers: ['web_research', 'needs_citations'],
  track_open_source: ['web_research'],
  track_industry_events: ['web_research'],
  track_regulatory_changes: ['web_research', 'legal_reasoning'],
  analyze_ai_adoption: ['web_research'],
  track_ai_benchmarks: ['web_research'],
  analyze_org_structure: ['web_research'],
  compile_research_digest: ['web_research'],
  identify_research_gaps: ['web_research'],
  cross_reference_findings: ['web_research'],
  search_company_info: ['web_research'],
  search_crunchbase: ['web_research'],
  search_linkedin_profiles: ['web_research'],
  search_job_postings: ['web_research'],
  check_job_postings: ['web_research'],
  query_competitor_tech_stack: ['structured_extraction'],
  monitor_competitor_marketing: ['web_research'],
  analyze_market_trends: ['web_research'],
  get_trending_topics: ['web_research'],
  pulse_analyze_brand_website: ['web_research'],

  // Legal
  get_compliance_status: ['legal_reasoning', 'needs_citations'],
  get_contracts: ['legal_reasoning', 'needs_citations'],
  create_contract: ['legal_reasoning', 'needs_citations'],
  track_regulations: ['legal_reasoning'],
  update_compliance_item: ['legal_reasoning'],
  create_compliance_alert: ['legal_reasoning'],
  create_contract_review: ['legal_reasoning'],
  flag_contract_issue: ['legal_reasoning'],
  get_contract_renewals: ['legal_reasoning'],
  get_ip_portfolio: ['legal_reasoning'],
  create_ip_filing: ['legal_reasoning'],
  monitor_ip_infringement: ['legal_reasoning'],
  get_tax_calendar: ['legal_reasoning'],
  calculate_tax_estimate: ['legal_reasoning'],
  get_tax_research: ['legal_reasoning'],
  review_tax_strategy: ['legal_reasoning'],
  audit_data_flows: ['legal_reasoning'],
  check_data_retention: ['legal_reasoning'],
  get_privacy_requests: ['legal_reasoning'],
  audit_access_permissions: ['legal_reasoning'],
  create_signing_envelope: ['legal_reasoning'],
  send_template_envelope: ['simple_tool_calling'],
  check_envelope_status: ['structured_extraction'],
  list_envelopes: ['structured_extraction'],
  void_envelope: ['legal_reasoning'],
  resend_envelope: ['simple_tool_calling'],

  // Finance
  get_financials: ['financial_computation'],
  get_revenue_forecast: ['financial_computation', 'needs_code_execution'],
  get_customer_ltv: ['financial_computation', 'needs_code_execution'],
  calculate_unit_economics: ['financial_computation', 'needs_code_execution'],
  get_margin_analysis: ['financial_computation', 'needs_code_execution'],
  query_financials: ['financial_computation'],
  query_costs: ['financial_computation'],
  get_infrastructure_costs: ['financial_computation'],
  query_stripe_mrr: ['financial_computation'],
  query_stripe_subscriptions: ['financial_computation'],
  get_mrr_breakdown: ['financial_computation'],
  get_subscription_details: ['financial_computation'],
  get_churn_analysis: ['financial_computation'],
  get_stripe_invoices: ['financial_computation'],
  get_gcp_costs: ['financial_computation'],
  get_ai_model_costs: ['financial_computation'],
  get_vendor_costs: ['financial_computation'],
  get_cost_anomalies: ['financial_computation'],
  get_burn_rate: ['financial_computation'],
  create_budget: ['financial_computation'],
  check_budget_status: ['financial_computation'],
  get_unit_economics: ['financial_computation'],
  get_cash_balance: ['financial_computation'],
  get_cash_flow: ['financial_computation'],
  get_pending_transactions: ['financial_computation'],
  generate_financial_report: ['financial_computation'],
  query_stripe_revenue: ['financial_computation'],
  query_revenue_by_product: ['financial_computation'],
  query_revenue_by_cohort: ['financial_computation'],
  query_attribution: ['financial_computation'],
  calculate_ltv_cac: ['financial_computation'],
  forecast_revenue: ['financial_computation'],
  query_churn_revenue: ['financial_computation'],
  query_gcp_billing: ['financial_computation'],
  query_db_usage: ['financial_computation'],
  query_gemini_cost: ['financial_computation'],
  query_agent_run_costs: ['financial_computation'],
  identify_unused_resources: ['financial_computation'],
  calculate_cost_savings: ['financial_computation'],
  identify_waste: ['financial_computation'],
  calculate_unit_cost: ['financial_computation'],
  project_costs: ['financial_computation'],
  get_system_costs_realtime: ['financial_computation'],
  predict_capacity: ['financial_computation'],
  estimate_dev_spend: ['financial_computation'],

  // Evaluation + orchestration
  evaluate_assignment: ['nuanced_evaluation'],
  evaluate_team_output: ['nuanced_evaluation'],
  review_team_output: ['nuanced_evaluation'],
  create_performance_review: ['nuanced_evaluation'],
  read_founder_directives: ['orchestration'],
  create_work_assignments: ['orchestration'],
  dispatch_assignment: ['orchestration'],
  synthesize_team_deliverable: ['orchestration'],
  propose_directive: ['orchestration'],
  propose_initiative: ['orchestration'],
  activate_initiative: ['orchestration'],
  update_directive_progress: ['orchestration'],
  create_team_assignments: ['orchestration'],
  assign_team_task: ['orchestration'],
  check_team_status: ['orchestration'],
  check_team_assignments: ['orchestration'],
  escalate_to_sarah: ['orchestration'],
  grant_tool_access: ['orchestration'],
  revoke_tool_access: ['orchestration'],
  propose_authority_change: ['orchestration'],
  create_specialist_agent: ['orchestration'],
  list_my_created_agents: ['simple_tool_calling'],
  retire_created_agent: ['simple_tool_calling'],
  create_peer_work_request: ['orchestration'],
  create_decision: ['orchestration'],
  check_assignment_status: ['structured_extraction'],
  read_proposed_initiatives: ['structured_extraction'],
  read_initiatives: ['structured_extraction'],
  get_recent_activity: ['structured_extraction'],
  get_pending_decisions: ['structured_extraction'],
  check_escalations: ['structured_extraction'],
  get_product_metrics: ['structured_extraction'],
  read_company_memory: ['structured_extraction'],
  get_org_chart: ['structured_extraction'],
  get_agent_performance_summary: ['structured_extraction'],
  get_team_dynamics: ['structured_extraction'],
  request_peer_work: ['simple_tool_calling'],
  create_handoff: ['simple_tool_calling'],
  peer_data_request: ['simple_tool_calling'],
  send_briefing: ['simple_tool_calling'],

  // Collective intelligence + graph
  get_company_vitals: ['structured_extraction'],
  update_company_vitals: ['structured_extraction'],
  update_vitals_highlights: ['simple_tool_calling'],
  contribute_knowledge: ['simple_tool_calling'],
  promote_to_org_knowledge: ['simple_tool_calling'],
  get_org_knowledge: ['structured_extraction'],
  read_company_doctrine: ['structured_extraction'],
  create_knowledge_route: ['simple_tool_calling'],
  get_knowledge_routes: ['structured_extraction'],
  detect_contradictions: ['structured_extraction'],
  record_process_pattern: ['simple_tool_calling'],
  get_process_patterns: ['structured_extraction'],
  get_authority_proposals: ['structured_extraction'],
  trace_causes: ['structured_extraction'],
  trace_impact: ['structured_extraction'],
  query_knowledge_graph: ['structured_extraction'],
  add_knowledge: ['simple_tool_calling'],
  add_graph_node: ['simple_tool_calling'],
  add_graph_edge: ['simple_tool_calling'],

  // Design system + Figma + Canva + assets
  get_figma_file: ['structured_extraction'],
  export_figma_images: ['simple_tool_calling'],
  get_figma_image_fills: ['structured_extraction'],
  get_figma_components: ['structured_extraction'],
  get_figma_team_components: ['structured_extraction'],
  get_figma_styles: ['structured_extraction'],
  get_figma_team_styles: ['structured_extraction'],
  get_figma_comments: ['structured_extraction'],
  post_figma_comment: ['simple_tool_calling'],
  resolve_figma_comment: ['simple_tool_calling'],
  get_figma_file_metadata: ['structured_extraction'],
  get_figma_version_history: ['structured_extraction'],
  get_figma_team_projects: ['structured_extraction'],
  get_figma_project_files: ['structured_extraction'],
  get_figma_dev_resources: ['structured_extraction'],
  create_figma_dev_resource: ['code_generation'],
  manage_figma_webhooks: ['simple_tool_calling'],
  create_canva_design: ['creative_writing'],
  get_canva_design: ['structured_extraction'],
  search_canva_designs: ['structured_extraction'],
  list_canva_brand_templates: ['structured_extraction'],
  get_canva_template_fields: ['structured_extraction'],
  generate_canva_design: ['creative_writing'],
  export_canva_design: ['simple_tool_calling'],
  upload_canva_asset: ['simple_tool_calling'],
  create_logo_variation: ['creative_writing'],
  restyle_logo: ['creative_writing'],
  create_social_avatar: ['creative_writing'],
  generate_image: ['creative_writing'],
  generate_and_publish_asset: ['creative_writing'],
  upload_asset: ['simple_tool_calling'],
  list_assets: ['structured_extraction'],
  optimize_image: ['simple_tool_calling'],
  generate_favicon_set: ['creative_writing'],
  publish_asset_deliverable: ['simple_tool_calling'],

  // Product + marketing
  query_analytics_events: ['structured_extraction'],
  get_usage_metrics: ['structured_extraction'],
  get_funnel_analysis: ['structured_extraction'],
  get_cohort_retention: ['structured_extraction'],
  get_feature_usage: ['structured_extraction'],
  segment_users: ['structured_extraction'],
  create_survey: ['creative_writing'],
  get_survey_results: ['structured_extraction'],
  analyze_support_tickets: ['structured_extraction'],
  get_user_feedback: ['structured_extraction'],
  create_user_persona: ['creative_writing'],
  track_competitor: ['web_research'],
  get_competitor_profile: ['structured_extraction'],
  update_competitor_profile: ['simple_tool_calling'],
  compare_features: ['structured_extraction'],
  track_competitor_pricing: ['web_research'],
  monitor_competitor_launches: ['web_research'],
  get_market_landscape: ['web_research'],
  create_roadmap_item: ['structured_extraction'],
  score_feature_rice: ['structured_extraction'],
  get_roadmap: ['structured_extraction'],
  update_roadmap_item: ['structured_extraction'],
  get_feature_requests: ['structured_extraction'],
  manage_feature_flags: ['simple_tool_calling'],
  create_content_draft: ['creative_writing'],
  update_content_draft: ['creative_writing'],
  get_content_drafts: ['structured_extraction'],
  submit_content_for_review: ['simple_tool_calling'],
  approve_content_draft: ['simple_tool_calling'],
  reject_content_draft: ['simple_tool_calling'],
  publish_content: ['simple_tool_calling'],
  get_content_metrics: ['structured_extraction'],
  get_content_calendar: ['structured_extraction'],
  generate_content_image: ['creative_writing'],
  get_search_performance: ['structured_extraction'],
  get_seo_data: ['structured_extraction'],
  track_keyword_rankings: ['structured_extraction'],
  analyze_page_seo: ['structured_extraction'],
  get_indexing_status: ['structured_extraction'],
  submit_sitemap: ['simple_tool_calling'],
  update_seo_data: ['simple_tool_calling'],
  get_backlink_profile: ['structured_extraction'],
  schedule_social_post: ['simple_tool_calling'],
  get_scheduled_posts: ['structured_extraction'],
  get_social_metrics: ['structured_extraction'],
  get_post_performance: ['structured_extraction'],
  get_social_audience: ['structured_extraction'],
  reply_to_social: ['creative_writing'],
  get_mailchimp_lists: ['structured_extraction'],
  get_mailchimp_members: ['structured_extraction'],
  get_mailchimp_segments: ['structured_extraction'],
  create_mailchimp_campaign: ['creative_writing'],
  set_campaign_content: ['creative_writing'],
  send_test_campaign: ['simple_tool_calling'],
  send_campaign: ['simple_tool_calling'],
  get_campaign_report: ['structured_extraction'],
  get_campaign_list: ['structured_extraction'],
  manage_mailchimp_tags: ['simple_tool_calling'],
  send_transactional_email: ['simple_tool_calling'],
  get_mandrill_stats: ['structured_extraction'],
  search_mandrill_messages: ['structured_extraction'],
  get_mandrill_templates: ['structured_extraction'],
  render_mandrill_template: ['simple_tool_calling'],
  create_experiment: ['structured_extraction'],
  get_experiment_results: ['structured_extraction'],
  get_attribution_data: ['structured_extraction'],
  capture_lead: ['simple_tool_calling'],
  get_lead_pipeline: ['structured_extraction'],
  score_lead: ['structured_extraction'],
  get_marketing_dashboard: ['structured_extraction'],
  draft_blog_post: ['creative_writing'],
  draft_social_post: ['creative_writing'],
  draft_case_study: ['creative_writing'],
  draft_email: ['creative_writing'],
  store_intel: ['simple_tool_calling'],
  analyze_tech_stack: ['structured_extraction'],
  compile_dossier: ['creative_writing'],
  query_content_performance: ['structured_extraction'],
  query_top_performing_content: ['structured_extraction'],
  query_seo_rankings: ['structured_extraction'],
  query_keyword_data: ['structured_extraction'],
  discover_keywords: ['web_research'],
  query_competitor_rankings: ['structured_extraction'],
  query_backlinks: ['structured_extraction'],
  query_search_console: ['structured_extraction'],
  analyze_content_seo: ['structured_extraction'],
  query_social_metrics: ['structured_extraction'],
  query_post_performance: ['structured_extraction'],
  query_optimal_times: ['structured_extraction'],
  query_audience_demographics: ['structured_extraction'],
  monitor_mentions: ['web_research'],

  // Ops + platform
  get_platform_health: ['structured_extraction'],
  get_cloud_run_metrics: ['structured_extraction'],
  write_health_report: ['creative_writing'],
  write_financial_report: ['financial_computation'],
  write_product_analysis: ['nuanced_evaluation'],
  write_content: ['creative_writing'],
  write_company_memory: ['creative_writing'],
  write_pipeline_report: ['nuanced_evaluation'],
  write_design_audit: ['visual_analysis'],
  query_agent_runs: ['structured_extraction', 'low_complexity'],
  query_agent_health: ['structured_extraction', 'low_complexity'],
  query_data_sync_status: ['structured_extraction', 'low_complexity'],
  query_events_backlog: ['structured_extraction'],
  query_cost_trends: ['financial_computation'],
  trigger_agent_run: ['simple_tool_calling'],
  retry_failed_run: ['simple_tool_calling'],
  retry_data_sync: ['simple_tool_calling'],
  pause_agent: ['simple_tool_calling'],
  resume_agent: ['simple_tool_calling'],
  create_incident: ['simple_tool_calling'],
  resolve_incident: ['simple_tool_calling'],
  post_system_status: ['simple_tool_calling'],
  rollup_agent_performance: ['structured_extraction'],
  detect_milestones: ['structured_extraction'],
  update_growth_areas: ['simple_tool_calling'],
  query_cloud_run_metrics: ['structured_extraction'],
  run_health_check: ['structured_extraction'],
  query_gemini_latency: ['structured_extraction'],
  query_db_health: ['structured_extraction'],
  query_uptime: ['structured_extraction'],
  query_cache_metrics: ['structured_extraction'],
  query_pipeline_metrics: ['structured_extraction'],
  query_resource_utilization: ['structured_extraction'],
  query_cold_starts: ['structured_extraction'],
  create_bug_report: ['simple_tool_calling'],
  scale_service: ['simple_tool_calling'],
  run_cohort_analysis: ['structured_extraction'],
  design_experiment: ['simple_tool_calling'],
  query_user_analytics: ['structured_extraction'],
  query_build_metadata: ['structured_extraction'],
  query_onboarding_funnel: ['structured_extraction'],
  query_churn_data: ['structured_extraction'],
  query_first_build_metrics: ['structured_extraction'],
  query_drop_off_points: ['structured_extraction'],
  query_welcome_email_metrics: ['structured_extraction'],
  query_activation_rate: ['structured_extraction'],
  query_template_usage: ['structured_extraction'],
  design_onboarding_experiment: ['simple_tool_calling'],
  query_support_tickets: ['structured_extraction'],
  classify_ticket: ['simple_tool_calling'],
  respond_to_ticket: ['simple_tool_calling'],
  escalate_ticket: ['simple_tool_calling'],
  query_knowledge_base: ['structured_extraction'],
  batch_similar_tickets: ['structured_extraction'],
  comment_on_pr: ['simple_tool_calling'],
  get_agent_health_dashboard: ['structured_extraction'],
  get_event_bus_health: ['structured_extraction'],
  get_data_freshness: ['structured_extraction'],
  get_access_matrix: ['simple_tool_calling'],
  provision_access: ['simple_tool_calling'],
  revoke_access: ['simple_tool_calling'],
  audit_access: ['structured_extraction'],
  rotate_secrets: ['simple_tool_calling'],
  get_platform_audit_log: ['structured_extraction'],
  create_status_report: ['creative_writing'],

  // HR + admin
  update_agent_profile: ['simple_tool_calling'],
  create_onboarding_plan: ['simple_tool_calling'],
  run_engagement_survey: ['simple_tool_calling'],
  entra_get_user_profile: ['structured_extraction'],
  entra_update_user_profile: ['simple_tool_calling'],
  entra_upload_user_photo: ['simple_tool_calling'],
  entra_set_manager: ['simple_tool_calling'],
  entra_hr_assign_license: ['simple_tool_calling'],
  entra_audit_profiles: ['structured_extraction'],
  list_users: ['structured_extraction'],
  get_user: ['structured_extraction'],
  list_channels: ['structured_extraction'],
  list_channel_members: ['structured_extraction'],
  add_channel_member: ['simple_tool_calling'],
  create_channel: ['simple_tool_calling'],
  post_to_channel: ['simple_tool_calling'],
  list_calendar_events: ['structured_extraction'],
  write_admin_log: ['simple_tool_calling'],
  list_project_iam: ['structured_extraction'],
  grant_project_role: ['simple_tool_calling'],
  revoke_project_role: ['simple_tool_calling'],
  list_service_accounts: ['structured_extraction'],
  create_service_account: ['simple_tool_calling'],
  list_secrets: ['structured_extraction'],
  get_secret_iam: ['structured_extraction'],
  grant_secret_access: ['simple_tool_calling'],
  revoke_secret_access: ['simple_tool_calling'],
  run_access_audit: ['structured_extraction'],
  run_onboarding: ['simple_tool_calling'],
  entra_list_users: ['structured_extraction'],
  entra_create_user: ['simple_tool_calling'],
  entra_disable_user: ['simple_tool_calling'],
  entra_list_groups: ['structured_extraction'],
  entra_list_group_members: ['structured_extraction'],
  entra_add_group_member: ['simple_tool_calling'],
  entra_remove_group_member: ['simple_tool_calling'],
  entra_list_directory_roles: ['structured_extraction'],
  entra_assign_directory_role: ['simple_tool_calling'],
  entra_list_app_registrations: ['structured_extraction'],
  entra_list_licenses: ['structured_extraction'],
  entra_assign_license: ['simple_tool_calling'],
  entra_revoke_license: ['simple_tool_calling'],
  entra_audit_sign_ins: ['structured_extraction'],
  send_dm: ['simple_tool_calling'],
  create_calendar_event: ['simple_tool_calling'],
  upload_to_sharepoint: ['simple_tool_calling'],

  // Tooling + misc
  check_table_schema: ['structured_extraction'],
  diagnose_column_error: ['structured_extraction'],
  list_tables: ['structured_extraction'],
  check_tool_health: ['deterministic_possible'],
  view_access_matrix: ['structured_extraction'],
  view_pending_grant_requests: ['structured_extraction'],
  get_tool_request_status: ['structured_extraction'],
  check_tool_request_status: ['structured_extraction'],
  list_tool_requests: ['structured_extraction'],
  review_tool_request: ['orchestration'],
  register_tool: ['simple_tool_calling'],
  deactivate_tool: ['simple_tool_calling'],
  list_registered_tools: ['structured_extraction'],
  query_logs: ['structured_extraction'],
  query_customers: ['structured_extraction'],
  check_system_health: ['structured_extraction'],
  file_decision: ['nuanced_evaluation'],

  // Design implementation sub-agents
  query_design_tokens: ['structured_extraction'],
  query_component_implementations: ['structured_extraction'],
  save_component_spec: ['code_generation'],
  push_component: ['code_generation'],
  create_component_branch: ['code_generation'],
  create_component_pr: ['code_generation'],
  save_component_implementation: ['code_generation'],
  query_component_specs: ['structured_extraction'],
  query_my_implementations: ['structured_extraction'],
  grade_build: ['nuanced_evaluation'],
  query_build_grades: ['structured_extraction'],
  save_template_variant: ['code_generation'],
  query_template_variants: ['structured_extraction'],
  update_template_status: ['simple_tool_calling'],
  query_build_grades_by_template: ['structured_extraction'],

  // Customer Teams output
  post_to_customer_teams: ['simple_tool_calling'],
  request_teams_approval: ['simple_tool_calling'],

  // Routing helpers
  who_handles: ['simple_tool_calling'],
  get_agent_directory: ['simple_tool_calling'],
};
